// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messagePB.proto

package com.jarvis.zcontrol.protocol;

public final class MessagePB {
  private MessagePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string funName = 1;
    /**
     * <code>required string funName = 1;</code>
     */
    boolean hasFunName();
    /**
     * <code>required string funName = 1;</code>
     */
    java.lang.String getFunName();
    /**
     * <code>required string funName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFunNameBytes();

    // required string computerName = 2;
    /**
     * <code>required string computerName = 2;</code>
     */
    boolean hasComputerName();
    /**
     * <code>required string computerName = 2;</code>
     */
    java.lang.String getComputerName();
    /**
     * <code>required string computerName = 2;</code>
     */
    com.google.protobuf.ByteString
        getComputerNameBytes();

    // required string userName = 3;
    /**
     * <code>required string userName = 3;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string ip = 4;
    /**
     * <code>required string ip = 4;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 4;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // required string messageBody = 5;
    /**
     * <code>required string messageBody = 5;</code>
     */
    boolean hasMessageBody();
    /**
     * <code>required string messageBody = 5;</code>
     */
    java.lang.String getMessageBody();
    /**
     * <code>required string messageBody = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageBodyBytes();
  }
  /**
   * Protobuf type {@code com.jarvis.zcontrol.protocol.MessageProtocol}
   */
  public static final class MessageProtocol extends
      com.google.protobuf.GeneratedMessage
      implements MessageProtocolOrBuilder {
    // Use MessageProtocol.newBuilder() to construct.
    private MessageProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageProtocol defaultInstance;
    public static MessageProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public MessageProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              funName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              computerName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              ip_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              messageBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jarvis.zcontrol.protocol.MessagePB.internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jarvis.zcontrol.protocol.MessagePB.internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.class, com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageProtocol> PARSER =
        new com.google.protobuf.AbstractParser<MessageProtocol>() {
      public MessageProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string funName = 1;
    public static final int FUNNAME_FIELD_NUMBER = 1;
    private java.lang.Object funName_;
    /**
     * <code>required string funName = 1;</code>
     */
    public boolean hasFunName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string funName = 1;</code>
     */
    public java.lang.String getFunName() {
      java.lang.Object ref = funName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          funName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string funName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFunNameBytes() {
      java.lang.Object ref = funName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        funName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string computerName = 2;
    public static final int COMPUTERNAME_FIELD_NUMBER = 2;
    private java.lang.Object computerName_;
    /**
     * <code>required string computerName = 2;</code>
     */
    public boolean hasComputerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string computerName = 2;</code>
     */
    public java.lang.String getComputerName() {
      java.lang.Object ref = computerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          computerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string computerName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getComputerNameBytes() {
      java.lang.Object ref = computerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        computerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string userName = 3;
    public static final int USERNAME_FIELD_NUMBER = 3;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 3;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ip = 4;
    public static final int IP_FIELD_NUMBER = 4;
    private java.lang.Object ip_;
    /**
     * <code>required string ip = 4;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string ip = 4;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string messageBody = 5;
    public static final int MESSAGEBODY_FIELD_NUMBER = 5;
    private java.lang.Object messageBody_;
    /**
     * <code>required string messageBody = 5;</code>
     */
    public boolean hasMessageBody() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string messageBody = 5;</code>
     */
    public java.lang.String getMessageBody() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string messageBody = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBodyBytes() {
      java.lang.Object ref = messageBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      funName_ = "";
      computerName_ = "";
      userName_ = "";
      ip_ = "";
      messageBody_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFunName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComputerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFunNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getComputerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMessageBodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFunNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getComputerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMessageBodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jarvis.zcontrol.protocol.MessageProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jarvis.zcontrol.protocol.MessagePB.MessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jarvis.zcontrol.protocol.MessagePB.internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jarvis.zcontrol.protocol.MessagePB.internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.class, com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.Builder.class);
      }

      // Construct using com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        funName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        computerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        messageBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jarvis.zcontrol.protocol.MessagePB.internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_descriptor;
      }

      public com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol getDefaultInstanceForType() {
        return com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.getDefaultInstance();
      }

      public com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol build() {
        com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol buildPartial() {
        com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol result = new com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.funName_ = funName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.computerName_ = computerName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageBody_ = messageBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol) {
          return mergeFrom((com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol other) {
        if (other == com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol.getDefaultInstance()) return this;
        if (other.hasFunName()) {
          bitField0_ |= 0x00000001;
          funName_ = other.funName_;
          onChanged();
        }
        if (other.hasComputerName()) {
          bitField0_ |= 0x00000002;
          computerName_ = other.computerName_;
          onChanged();
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000004;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000008;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasMessageBody()) {
          bitField0_ |= 0x00000010;
          messageBody_ = other.messageBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFunName()) {
          
          return false;
        }
        if (!hasComputerName()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasMessageBody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jarvis.zcontrol.protocol.MessagePB.MessageProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string funName = 1;
      private java.lang.Object funName_ = "";
      /**
       * <code>required string funName = 1;</code>
       */
      public boolean hasFunName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string funName = 1;</code>
       */
      public java.lang.String getFunName() {
        java.lang.Object ref = funName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          funName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string funName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFunNameBytes() {
        java.lang.Object ref = funName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          funName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string funName = 1;</code>
       */
      public Builder setFunName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        funName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string funName = 1;</code>
       */
      public Builder clearFunName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        funName_ = getDefaultInstance().getFunName();
        onChanged();
        return this;
      }
      /**
       * <code>required string funName = 1;</code>
       */
      public Builder setFunNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        funName_ = value;
        onChanged();
        return this;
      }

      // required string computerName = 2;
      private java.lang.Object computerName_ = "";
      /**
       * <code>required string computerName = 2;</code>
       */
      public boolean hasComputerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string computerName = 2;</code>
       */
      public java.lang.String getComputerName() {
        java.lang.Object ref = computerName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          computerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string computerName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getComputerNameBytes() {
        java.lang.Object ref = computerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          computerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string computerName = 2;</code>
       */
      public Builder setComputerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        computerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string computerName = 2;</code>
       */
      public Builder clearComputerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        computerName_ = getDefaultInstance().getComputerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string computerName = 2;</code>
       */
      public Builder setComputerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        computerName_ = value;
        onChanged();
        return this;
      }

      // required string userName = 3;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 3;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string ip = 4;
      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 4;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string ip = 4;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 4;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 4;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 4;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }

      // required string messageBody = 5;
      private java.lang.Object messageBody_ = "";
      /**
       * <code>required string messageBody = 5;</code>
       */
      public boolean hasMessageBody() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string messageBody = 5;</code>
       */
      public java.lang.String getMessageBody() {
        java.lang.Object ref = messageBody_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          messageBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string messageBody = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBodyBytes() {
        java.lang.Object ref = messageBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string messageBody = 5;</code>
       */
      public Builder setMessageBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        messageBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string messageBody = 5;</code>
       */
      public Builder clearMessageBody() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageBody_ = getDefaultInstance().getMessageBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string messageBody = 5;</code>
       */
      public Builder setMessageBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        messageBody_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jarvis.zcontrol.protocol.MessageProtocol)
    }

    static {
      defaultInstance = new MessageProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jarvis.zcontrol.protocol.MessageProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017messagePB.proto\022\034com.jarvis.zcontrol.p" +
      "rotocol\"k\n\017MessageProtocol\022\017\n\007funName\030\001 " +
      "\002(\t\022\024\n\014computerName\030\002 \002(\t\022\020\n\010userName\030\003 " +
      "\002(\t\022\n\n\002ip\030\004 \002(\t\022\023\n\013messageBody\030\005 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_jarvis_zcontrol_protocol_MessageProtocol_descriptor,
              new java.lang.String[] { "FunName", "ComputerName", "UserName", "Ip", "MessageBody", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
