// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sendCommandPB.proto

package com.jarvis.zcontrol.protocol;

public final class SendCommandPB {
  private SendCommandPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SendCommandProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;
    /**
     * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
     */
    boolean hasSpringBeanProtocol();
    /**
     * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
     */
    com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol getSpringBeanProtocol();
    /**
     * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
     */
    com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder getSpringBeanProtocolOrBuilder();

    // required string command = 2;
    /**
     * <code>required string command = 2;</code>
     */
    boolean hasCommand();
    /**
     * <code>required string command = 2;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>required string command = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();
  }
  /**
   * Protobuf type {@code com.jarvis.zcontrol.protocol.SendCommandProtocol}
   */
  public static final class SendCommandProtocol extends
      com.google.protobuf.GeneratedMessage
      implements SendCommandProtocolOrBuilder {
    // Use SendCommandProtocol.newBuilder() to construct.
    private SendCommandProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendCommandProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendCommandProtocol defaultInstance;
    public static SendCommandProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public SendCommandProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendCommandProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = springBeanProtocol_.toBuilder();
              }
              springBeanProtocol_ = input.readMessage(com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(springBeanProtocol_);
                springBeanProtocol_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              command_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jarvis.zcontrol.protocol.SendCommandPB.internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jarvis.zcontrol.protocol.SendCommandPB.internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.class, com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<SendCommandProtocol> PARSER =
        new com.google.protobuf.AbstractParser<SendCommandProtocol>() {
      public SendCommandProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendCommandProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendCommandProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;
    public static final int SPRINGBEANPROTOCOL_FIELD_NUMBER = 1;
    private com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol springBeanProtocol_;
    /**
     * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
     */
    public boolean hasSpringBeanProtocol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
     */
    public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol getSpringBeanProtocol() {
      return springBeanProtocol_;
    }
    /**
     * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
     */
    public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder getSpringBeanProtocolOrBuilder() {
      return springBeanProtocol_;
    }

    // required string command = 2;
    public static final int COMMAND_FIELD_NUMBER = 2;
    private java.lang.Object command_;
    /**
     * <code>required string command = 2;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string command = 2;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string command = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      springBeanProtocol_ = com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance();
      command_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSpringBeanProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSpringBeanProtocol().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, springBeanProtocol_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCommandBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, springBeanProtocol_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCommandBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jarvis.zcontrol.protocol.SendCommandProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jarvis.zcontrol.protocol.SendCommandPB.internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jarvis.zcontrol.protocol.SendCommandPB.internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.class, com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.Builder.class);
      }

      // Construct using com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSpringBeanProtocolFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (springBeanProtocolBuilder_ == null) {
          springBeanProtocol_ = com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance();
        } else {
          springBeanProtocolBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jarvis.zcontrol.protocol.SendCommandPB.internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_descriptor;
      }

      public com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol getDefaultInstanceForType() {
        return com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.getDefaultInstance();
      }

      public com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol build() {
        com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol buildPartial() {
        com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol result = new com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (springBeanProtocolBuilder_ == null) {
          result.springBeanProtocol_ = springBeanProtocol_;
        } else {
          result.springBeanProtocol_ = springBeanProtocolBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.command_ = command_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol) {
          return mergeFrom((com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol other) {
        if (other == com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol.getDefaultInstance()) return this;
        if (other.hasSpringBeanProtocol()) {
          mergeSpringBeanProtocol(other.getSpringBeanProtocol());
        }
        if (other.hasCommand()) {
          bitField0_ |= 0x00000002;
          command_ = other.command_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSpringBeanProtocol()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        if (!getSpringBeanProtocol().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jarvis.zcontrol.protocol.SendCommandPB.SendCommandProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;
      private com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol springBeanProtocol_ = com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder> springBeanProtocolBuilder_;
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public boolean hasSpringBeanProtocol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol getSpringBeanProtocol() {
        if (springBeanProtocolBuilder_ == null) {
          return springBeanProtocol_;
        } else {
          return springBeanProtocolBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public Builder setSpringBeanProtocol(com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol value) {
        if (springBeanProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          springBeanProtocol_ = value;
          onChanged();
        } else {
          springBeanProtocolBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public Builder setSpringBeanProtocol(
          com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder builderForValue) {
        if (springBeanProtocolBuilder_ == null) {
          springBeanProtocol_ = builderForValue.build();
          onChanged();
        } else {
          springBeanProtocolBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public Builder mergeSpringBeanProtocol(com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol value) {
        if (springBeanProtocolBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              springBeanProtocol_ != com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance()) {
            springBeanProtocol_ =
              com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.newBuilder(springBeanProtocol_).mergeFrom(value).buildPartial();
          } else {
            springBeanProtocol_ = value;
          }
          onChanged();
        } else {
          springBeanProtocolBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public Builder clearSpringBeanProtocol() {
        if (springBeanProtocolBuilder_ == null) {
          springBeanProtocol_ = com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance();
          onChanged();
        } else {
          springBeanProtocolBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder getSpringBeanProtocolBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSpringBeanProtocolFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder getSpringBeanProtocolOrBuilder() {
        if (springBeanProtocolBuilder_ != null) {
          return springBeanProtocolBuilder_.getMessageOrBuilder();
        } else {
          return springBeanProtocol_;
        }
      }
      /**
       * <code>required .com.jarvis.zcontrol.protocol.SpringBeanProtocol springBeanProtocol = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder> 
          getSpringBeanProtocolFieldBuilder() {
        if (springBeanProtocolBuilder_ == null) {
          springBeanProtocolBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder>(
                  springBeanProtocol_,
                  getParentForChildren(),
                  isClean());
          springBeanProtocol_ = null;
        }
        return springBeanProtocolBuilder_;
      }

      // required string command = 2;
      private java.lang.Object command_ = "";
      /**
       * <code>required string command = 2;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string command = 2;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string command = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string command = 2;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 2;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 2;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jarvis.zcontrol.protocol.SendCommandProtocol)
    }

    static {
      defaultInstance = new SendCommandProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jarvis.zcontrol.protocol.SendCommandProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023sendCommandPB.proto\022\034com.jarvis.zcontr" +
      "ol.protocol\032\022springBeanPB.proto\"t\n\023SendC" +
      "ommandProtocol\022L\n\022springBeanProtocol\030\001 \002" +
      "(\01320.com.jarvis.zcontrol.protocol.Spring" +
      "BeanProtocol\022\017\n\007command\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_jarvis_zcontrol_protocol_SendCommandProtocol_descriptor,
              new java.lang.String[] { "SpringBeanProtocol", "Command", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jarvis.zcontrol.protocol.SpringBeanPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
