// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: springBeanPB.proto

package com.jarvis.zcontrol.protocol;

public final class SpringBeanPB {
  private SpringBeanPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SpringBeanProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string beanName = 1;
    /**
     * <code>required string beanName = 1;</code>
     */
    boolean hasBeanName();
    /**
     * <code>required string beanName = 1;</code>
     */
    java.lang.String getBeanName();
    /**
     * <code>required string beanName = 1;</code>
     */
    com.google.protobuf.ByteString
        getBeanNameBytes();
  }
  /**
   * Protobuf type {@code com.jarvis.zcontrol.protocol.SpringBeanProtocol}
   */
  public static final class SpringBeanProtocol extends
      com.google.protobuf.GeneratedMessage
      implements SpringBeanProtocolOrBuilder {
    // Use SpringBeanProtocol.newBuilder() to construct.
    private SpringBeanProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpringBeanProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpringBeanProtocol defaultInstance;
    public static SpringBeanProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public SpringBeanProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpringBeanProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              beanName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jarvis.zcontrol.protocol.SpringBeanPB.internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jarvis.zcontrol.protocol.SpringBeanPB.internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.class, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<SpringBeanProtocol> PARSER =
        new com.google.protobuf.AbstractParser<SpringBeanProtocol>() {
      public SpringBeanProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpringBeanProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpringBeanProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string beanName = 1;
    public static final int BEANNAME_FIELD_NUMBER = 1;
    private java.lang.Object beanName_;
    /**
     * <code>required string beanName = 1;</code>
     */
    public boolean hasBeanName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string beanName = 1;</code>
     */
    public java.lang.String getBeanName() {
      java.lang.Object ref = beanName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          beanName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string beanName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBeanNameBytes() {
      java.lang.Object ref = beanName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        beanName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      beanName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBeanName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBeanNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBeanNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jarvis.zcontrol.protocol.SpringBeanProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jarvis.zcontrol.protocol.SpringBeanPB.internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jarvis.zcontrol.protocol.SpringBeanPB.internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.class, com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.Builder.class);
      }

      // Construct using com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        beanName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jarvis.zcontrol.protocol.SpringBeanPB.internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_descriptor;
      }

      public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol getDefaultInstanceForType() {
        return com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance();
      }

      public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol build() {
        com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol buildPartial() {
        com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol result = new com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.beanName_ = beanName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol) {
          return mergeFrom((com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol other) {
        if (other == com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol.getDefaultInstance()) return this;
        if (other.hasBeanName()) {
          bitField0_ |= 0x00000001;
          beanName_ = other.beanName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBeanName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jarvis.zcontrol.protocol.SpringBeanPB.SpringBeanProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string beanName = 1;
      private java.lang.Object beanName_ = "";
      /**
       * <code>required string beanName = 1;</code>
       */
      public boolean hasBeanName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string beanName = 1;</code>
       */
      public java.lang.String getBeanName() {
        java.lang.Object ref = beanName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          beanName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string beanName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBeanNameBytes() {
        java.lang.Object ref = beanName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          beanName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string beanName = 1;</code>
       */
      public Builder setBeanName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        beanName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string beanName = 1;</code>
       */
      public Builder clearBeanName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        beanName_ = getDefaultInstance().getBeanName();
        onChanged();
        return this;
      }
      /**
       * <code>required string beanName = 1;</code>
       */
      public Builder setBeanNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        beanName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jarvis.zcontrol.protocol.SpringBeanProtocol)
    }

    static {
      defaultInstance = new SpringBeanProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jarvis.zcontrol.protocol.SpringBeanProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022springBeanPB.proto\022\034com.jarvis.zcontro" +
      "l.protocol\"&\n\022SpringBeanProtocol\022\020\n\010bean" +
      "Name\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_jarvis_zcontrol_protocol_SpringBeanProtocol_descriptor,
              new java.lang.String[] { "BeanName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
